[package]
name = "near-jsonrpc-client"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/near/near-jsonrpc-client-rs"
homepage = "https://github.com/near/near-jsonrpc-client-rs"
description = "Generic, low-level interfaces for interacting with the NEAR Protocol via JSON_RPC / HTTP"

[dependencies]
# todo! remove this once nearcore has upgraded to stable actix
# todo! or if actix is no longer in the dependency graph
actix_derive = { version = "=0.6.0-beta.1" }

thiserror = "1.0.28"

reqwest = { version = "0.11.4", features = ["json"] }
lazy_static = "1.4.0"

borsh = "0.9"
serde = "1.0.127"
serde_json = "1.0.66"

near-primitives = { git = "https://github.com/near/nearcore", rev="b4925abb521f34cebcb45c10f2e010b219acc0ae" }
near-chain-configs = { git = "https://github.com/near/nearcore", rev="b4925abb521f34cebcb45c10f2e010b219acc0ae" }
near-client-primitives = { git = "https://github.com/near/nearcore", rev="b4925abb521f34cebcb45c10f2e010b219acc0ae" }
near-jsonrpc-primitives = { git = "https://github.com/near/nearcore", rev="b4925abb521f34cebcb45c10f2e010b219acc0ae" }

[dev-dependencies]
tokio = { version = "1.1", features = ["rt", "macros"] }

[features]
sandbox = []
adversarial = ["near-jsonrpc-primitives/adversarial"]
