[package]
name = "near-jsonrpc-client"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/near/near-jsonrpc-client-rs"
homepage = "https://github.com/near/near-jsonrpc-client-rs"
description = "Lower-level API for interfacing with the NEAR Protocol via JSONRPC"
categories = ["asynchronous", "api-bindings", "network-programming"]
keywords = ["near", "api", "jsonrpc", "rpc", "async"]

[dependencies]
thiserror = "1.0.28"

reqwest = { version = "0.11.4", features = ["json"] }
lazy_static = "1.4.0"

borsh = "0.9"
serde = "1.0.127"
serde_json = "1.0.66"

near-primitives = { git = "https://github.com/near/nearcore", rev = "a9b077485442fd9bc191b7eb2f2319ea2cfce818" }
near-chain-configs = { git = "https://github.com/near/nearcore", rev = "a9b077485442fd9bc191b7eb2f2319ea2cfce818" }
near-client-primitives = { git = "https://github.com/near/nearcore", rev = "a9b077485442fd9bc191b7eb2f2319ea2cfce818" }
near-jsonrpc-primitives = { git = "https://github.com/near/nearcore", rev = "a9b077485442fd9bc191b7eb2f2319ea2cfce818" }

[dev-dependencies]
tokio = { version = "1.1", features = ["rt", "macros"] }

[features]
any = []
sandbox = []
adversarial = []
